DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS conditions;
DROP TABLE IF EXISTS sources;
DROP TABLE IF EXISTS spells;
DROP TABLE IF EXISTS effects;

DROP DATABASE IF EXISTS the_wizards_db;